### ISSUE TITLE
Introduce Relevant Images

### ISSUE THREAD

**Issue by garrettbryant** [Team-Outbreak/item-finder#17]
Images would help the UI a lot.  It also may be useful for the user to be able to see what the item they are searching for actually looks like, as well as the relevant associations.

It would be ideal if we could integrate with Google's image search engine to be able to dynamically find relevant images for items rather than attempting to store images for each item.  Google's API is documented here: https://developers.google.com/custom-search/ (the image specific search API is deprecated, so this seems to be what we need).

As far as implementation goes, I think hovering/tapping an item to view a hovering tooltip-like UI with scrollable images would work best.

**Comment by sbryant-developer** [comment]
What's done:
- Associations can now be tapped and a relevant image is displayed from Google
- The API has quotas, so we're limiting how frequently it's hit
- This is focused mostly for mobile at the moment

What's not done (and if desired, will require new issues):
- Images for the searched item are not displayed
- The WEB interface isn't intuitive (which is fine)
- Only one image is displayed per item (to avoid spending too much time integrating a new interface component).

As far as implementation goes, I think hovering/tapping an item to view a hovering tooltip-like UI with scrollable images would work best.
