### ISSUE TITLE
Add The User Rating System

### ISSUE THREAD

**Issue by sbryant-developer** [Team-Outbreak/item-finder#7]
The user should be able to rate an association up or down.
These ratings will decrease/increase their relevancy in search results by modifying the association's "rating" attribute.

**Comment by garrettbryant** [comment]
This may require us to introduce a login process.  Unless we figure out an alternative way to restrict the same user from voting multiple over and over again.  Maybe it isn't too important to restrict this for now?
If we opt to require login before voting then we want to make logging in and/or creating an account as easy as possible so we don't deter many users.

**Comment by sbryant-developer** [comment]
Agreed, in the future, accounts definitely make sense. I'm thinking a double rating system: 'verifiedRating' and 'unverifiedRating'.
So non-account users can still rate, but it'll have less of an impact.

Maybe for now, stick to one rating & no accounts & maybe restrict it so that ratings for an association are ignored if the association has been updated in the last 60 seconds? I think that'll prevent 99% of potential spam/troll issues.
